image: golang:1
stages:
  - build

default:
  tags:
    - docker
    - linux

.build:
  stage: build
  variables:
    VERSION: $CI_COMMIT_BRANCH.$CI_PIPELINE_IID
  script:
   - make release
  artifacts:
    paths:
      - ./bin
    expire_in: 30 days

build_develop:
  extends: .build
  artifacts:
    paths:
      - ./bin
    expire_in: 24 hours
  rules:
   - if: '$CI_COMMIT_BRANCH =~ /^develop$/'